title: Into the Namespaces
name: Into the Namespaces
google_verification: null
email: lanphuongpham02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Forever in an endless pursuit of excellence
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://lanphgphm.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year:month:day/:title
github_username: lanphgphm
linkedin_username: lanphuongpham02

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
theme: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# collections:
#   category:
#     output: true
#     permalink: /category/:name
#   protected:
#     output: true
#     permalink: /protected/:title/

# defaults:
#   - scope:
#       path: ""
#       type: protected
#     values:
#       layout: protected.html
#       output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

